apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namescpace: kube-system
data:
  mapUsers:
    - username: arn:aws:iam::343818524685:user/eks-user
    username: eks-user
    groups:
      - system:masters
