apiVersion: apps/v1
kind: Deployment
metadata:
  name: javagradleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javagradleapp
template:
    metadata:
      labels:
        app: javagradleapp
 spec:
      containers:
        - name: java-container
          image: madhu1607/javagradle:latest  
          ports:
            - containerPort: 8080 
