name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Show Contents of build/libs Directory
      run: ls -R build/libs
    - name: Debug Docker Context
      run: |
        pwd
        ls -R
    - name: Print Secret Values
      run: |
         echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
         echo "DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}"
         
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: madhu1607
        password: 123456789@madhu
    - name: Build and Push Docker Image
      run: |
        docker build -t madhu1607/javagradle:latest .
        docker push madhu1607/javagradle:latest
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
        with:
          version: v1.27.4
      - name: Check if kubectl is installed
        run: |
          if ! command -v kubectl; then
            echo "kubectl is not installed"
            exit 1
          else
            echo "kubectl is installed"
          fi
      - name: Install kops
        run: |
           curl -LO "https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64"

           +x kops-linux-amd64

           sudo mv kops-linux-amd64 /usr/local/bin/kops
      - name: Check if kops installed
        run: |
          if ! command -v kops; then
            echo "kops not installed"
            exit 1
          else
            echo "kops is installed"
          fi
            

    # Version of kubect   version: # default is latest
    
      
    
         
