name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Show Contents of build/libs Directory
      run: ls -R build/libs
    - name: Debug Docker Context
      run: |
        pwd
        ls -R
    - name: Print Secret Values
      run: |
         echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
         echo "DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}"
         
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: madhu1607
        password: 123456789@madhu

    - name: Build and Push Docker Image
      run: |
        docker build -t madhu1607/javagradle:latest .
        docker push madhu1607/javagradle:latest
    
         
