name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bootJar
    - name: Show Contents of build/libs Directory
      run: ls -R build/libs
    - name: Debug Docker Context
      run: |
        pwd
        ls -R
    - name: Print Secret Values
      run: |
         echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
         echo "DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}"
         
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: madhu1607
        password: 123456789@madhu
    - name: Build and Push Docker Image
      run: |
        docker build -t madhu1607/javagradle:latest .
        docker push madhu1607/javagradle:latest

      #-name: Install eksctl
       # run: |
         #  curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
           #sudo mv /tmp/eksctl /usr/local/bin
      ##- name: Check if eksctl installed
       # run: |
         # if ! command -v eksctl; then
            #echo "eksctl not installed"
            #exit 1
          #else
            #echo "eksctl is installed"
          #fi
          
  kubernetes-deployment:
    runs-on: ubuntu-latest
    needs: [build-java]
    steps:
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
        with:
          version: v1.27.4
      - name: Check if kubectl is installed
        run: |
          if ! command -v kubectl; then
            echo "kubectl is not installed"
            exit 1
          else
            echo "kubectl is installed"
          fi
      - name: Checkout code
        uses: actions/checkout@v2
      - name: aws-configure 
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: AKIAVADJOLAGRTSYMES4
            aws-secret-access-key: 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
            aws-region: ap-southeast-1  

      - name: Configure kubectl
        run: |
          aws eks --region ap-southeast-1 update-kubeconfig --name madhucluster

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f deployment.yml
         
      
           
      

        
        
            

    
      
    
         
