name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
env:
  GKE_CLUSTER: cluster-springboot  
  GKE_ZONE: us-central1-c 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkouts code 
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bootJar
    - name: Show Contents of build/libs Directory
      run: ls -R build/libs
    - name: Debug Docker Context
      run: |
        pwd
        ls -R          
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: madhu1607
        password: 123456789@madhu
    - name: Build and Push Docker Image
      run: |
        docker build -t madhu1607/javagradle:latest .
        docker push madhu1607/javagradle:latest

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GKE_KEY }}
        project_id: modified-legacy-395815
    - name: Configure gcloud and kubectl
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}
    - name: Apply Kubernetes Resources
      run: |
        kubectl apply -f deployment.yml -f service.yml

      
      
      
      
      
      
            

    
      
    
         
