name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bootJar
    - name: Show Contents of build/libs Directory
      run: ls -R build/libs
    - name: Debug Docker Context
      run: |
        pwd
        ls -R
    - name: Print Secret Values
      run: |
         echo "DOCKER_USERNAME: ${{ Secrets.DOCKER_USERNAME }}"
         echo "DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}"
         
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: madhu1607
        password: 123456789@madhu
    - name: Build and Push Docker Image
      run: |
        docker build -t madhu1607/javagradle:latest .
        docker push madhu1607/javagradle:latest
          
  kubernetes-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
        with:
          version: v1.27.4
      - name: Check if kubectl is installed
        run: |
          if ! command -v kubectl; then
            echo "kubectl is not installed"
            exit 1
          else
            echo "kubectl is installed"
          fi
      - name: Checkout code
        uses: actions/checkout@v2
      - name: aws-configure 
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: AKIAVADJOLAGRDH345YW
            aws-secret-access-key: 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
            aws-region: ap-southeast-1 
            
     # - name: to check if it configured
     #   run: aws s3 ls

      - name: Authenticate kubectl with EKS cluster
        run: |
          aws eks update-kubeconfig --name madhucluster --region ap-southeast-1 --role-arn arn:aws:iam::343818524685:role/eksctl-madhucluster-cluster-ServiceRole-1XB2C3M2IO2T8
          
      - name: Display Updated Kubeconfig
        run: cat ~/.kube/config
        
      - name: Describe cluster
        run: aws eks describe-cluster --name madhucluster
        
      - name: list nodegroup
        run: aws eks list-nodegroups --cluster-name madhucluster
      - name: list nodes
        run: |
           aws eks update-kubeconfig --name madhucluster --region ap-southeast-1 --role-arn arn:aws:iam::343818524685:role/eksctl-madhucluster-cluster-ServiceRole-1XB2C3M2IO2T8
           kubectl get nodes
         
         
         
      
           
      

        
        
            

    
      
    
         
